### ISSUE TITLE
[Architecture] Add & configure a module bundler

### ISSUE THREAD

**Issue by VitorLuizC** [vue-unstyled-components/vue-unstyled-components#1]
We need a module bundler to transpile/compile from Vue single-file-component syntax + TypeScript to JavaScript module.

- [ ] ~Transpile Vue + Typescript component~;
- [x] Handle multiple files at once;
- [x] Exposes CommonJS module;

**Comment by VitorLuizC** [comment]
There are some module bundles and abstractions of theirs.

Module bundlers | `webpack` | `rollup` | `browserify` | `poi`  | `bili`
--------------- | --------- | -------- | ------------ | ------ | ------

I've tried `bili`, a rollup abstraction, because it simplicity and stuck into `rollup-plugin-vue` issue.

https://github.com/vuejs/rollup-plugin-vue/issues/105

Seems like rollup-plugin-vue can't support the best part of Vue + TypeScript which is components as classes. So, I'll write a build using multiple POI instances.

@guibarscevicius @viniazvd

**Comment by viniazvd** [comment]
**webpack always** 

https://github.com/Microsoft/TypeScript-Vue-Starter

**Comment by VitorLuizC** [comment]
I'm only declining because of complexity bundling all components down to CommonJS ES5 modules. Webpack handles poorly UMD & CommonJS single output's treeshaking and it's really hard to automatically grab components entries and output.

We need to discuss about components structure. I'm thinking about easy way to import each component.

```js
import Button from 'vue-unstyled-component/Button'
```

To do so we have to bundle components like example below.
```hs
compiles "Button/Button.vue" to "Button/index.js"
```

**Comment by VitorLuizC** [comment]
I'd dropped TypeScript support. With TypeScript, with/without decorators, even small components produces heavy bundles and seems buggy.

So, instead of creating a complex build & heavy bundles I've just dropped it.
