### ISSUE TITLE
[Component] Link component specs

### ISSUE THREAD

**Issue by VitorLuizC** [vue-unstyled-components/vue-unstyled-components#6]
Link component is useful to abstract `<router-link>`/`<nuxt-link>` and external link `<a>`. It also will be implemented as part of other unstyled components, like `Button`, `MenuItem` and `NavigationItem`.

**Specs**
- [x] Renders a link;
- [x] Uses `<slot>` as link content;
- [x] Support `<router-link>`, `<nuxt-link>` and `<a>`;

**Comment by VitorLuizC** [comment]
Because of global registered `nuxt-link` and `router-link` components. I'll need to mock these two and define some attribute to compare them (on tests).

```js
import Vue from 'vue';

Vue.component('nuxt-link', {
  template: '<a :href="to" data-component="nuxt-link"><slot /></a>',
  props: {
    to: String
  }
});

Vue.component('router-link', {
  template: '<a :href="to" data-component="router-link"><slot /></a>',
  props: {
    to: String
  }
});
```

**Comment by VitorLuizC** [comment]
I'm currently working on a CLink component with almost same specs and stuck in a problem. How can we avoid `is-nuxt`/`is-external` etc props on all definitions.

Some options are:

- Using a config object through Vue's prototype. So, install provide an option to define environment and we just need to check about External props, and it would be automatic.

```js
import Link from 'vue-unstyled-component/Link';

Vue.use(Link, {
  name: 'AppLink',
  environment: 'nuxt' // All links without http(s) stuff will be NuxtLinks
});
```

- Using prop `environment` which receives `'external'|'router'|'nuxt'`. And it will be required every time.

- Mix those two, and if on config we can't find `environment` it will be required.

// CC: @viniazvd @guibarscevicius

**Comment by VitorLuizC** [comment]
Environment | Element / Component
----------- | -------------------
external | `<a href={link}>{children}</a>`
router | `<router-link to={link}>{children}</router-link>`
nuxt | `<nuxt-link to={link}>{children}</nuxt-link>`

**Comment by viniazvd** [comment]
nice! i can't think of anything better.

**Comment by VitorLuizC** [comment]
I've changed "external" environment to "none", because external seems to open a link into a new browser's tab. So, now Link has a is-external prop.

// CC: @viniazvd @guibarscevicius
